### PR TITLE
added link_data --> clear_cache relationship to support repacking zarr nwbfiles

### PR DESCRIPTION
**Pull request by pauladkisson**
## Motivation

See https://github.com/catalystneuro/neuroconv/pull/1003

## Checklist

- [x] Did you update CHANGELOG.md with your changes?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf-zarr/blob/dev/docs/CONTRIBUTING.rst) document?
- [x] Have you ensured the PR clearly describes the problem and the solution?
- [x] Is your contribution compliant with our coding style? This can be checked running `ruff` from the source directory.
- [x] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/hdmf-dev/hdmf-zarr/pulls) for the same change?
- [x] Have you included the relevant issue number using "Fix #XXX" notation where XXX is the issue number? By including "Fix #XXX" you allow GitHub to close issue #XXX when the PR is merged.

### CODE REVIEW

**Comment by pauladkisson** [comment]
@oruebel, can you enable tests for this PR as well?

**Comment by pauladkisson** [comment]
@rly @oruebel CI tests pls?

**Comment by pauladkisson** [comment]
@rly @oruebel CI tests pls?

**Comment by pauladkisson** [comment]
Looks like this is passing all the tests, can we merge?

@rly @oruebel

**Comment by oruebel** [comment]
@rly @mavaylon1  can you please review. Export is more your area of expertise

**Comment by mavaylon1** [comment]
@pauladkisson @oruebel @rly I can take a gander this week.

**Comment by pauladkisson** [comment]
@mavaylon1, Still waiting for that gander...has it flown off-course? 🪿

**Comment by mavaylon1** [comment]
@pauladkisson Said gander has indeed flown off into the wilderness due to SFN. Let me review this tomorow.

**Comment by pauladkisson** [comment]
@mavaylon1, giving this a bump.

**Comment by mavaylon1** [comment]
So I am taking a look but I need more context. can you walk me through it since there are multiple links pointing elsewhere. I'll continue looking at this right now, but let me know as well @pauladkisson 

You are repacking zarr files but then you added "data is an h5py.Dataset" so I assume you are exporting at some point. 

Also in general it is better to be more explicit with variable names. Can you be more explicit instead using "o" and "c".

**Comment by pauladkisson** [comment]
> So I am taking a look but I need more context. can you walk me through it since there are multiple links pointing elsewhere.

Sure! I am working on a function to repack NWB files with more appropriate chunking/compression. But in order to do so, I need an option to redo chunking/compression when exporting -- hence the link_data -> clear_cache relationship.

Another related bug that pops when I enable this option: some datasets with strings are normally already decoded when writing from scratch, but when exporting, they need to be decoded again.

**Comment by pauladkisson** [comment]
> Also in general it is better to be more explicit with variable names. Can you be more explicit instead using "o" and "c".

This code is pretty much exact copy-paste from L1290-1300, so should be just as readable.

**Comment by mavaylon1** [comment]
> > Also in general it is better to be more explicit with variable names. Can you be more explicit instead using "o" and "c".
> 
> This code is pretty much exact copy-paste from L1290-1300, so should be just as readable.

Yeah both places aren't ideal, but I understand why you kept the style. I thought we cleaned that up already. All good though.

**Review by mavaylon1 — APPROVED** [review]

**Comment by mavaylon1** [comment]
@pauladkisson i am working on a change for exporting, but I think this PR should be good to go regardless.

**Comment by pauladkisson** [comment]
> @pauladkisson i am working on a change for exporting, but I think this PR should be good to go regardless.

Fantastic! Thanks for pushing this through @mavaylon1.

**Comment by pauladkisson** [comment]
FYI I'm not authorized to merge.

**Pull request merged**
