### PR TITLE
Debug the use of relative links

### LINKED ISSUE #44: Zarr links should be relative to root
Hi guys,

I was able to successfully export to NWB-zarr sorting info + waveforms and electrode table (using `neuroconv`).

I performed the conversion remotely and then downloaded the resulting files. When I try to read the file locally, I get a bad link error:
```
ValueError                                Traceback (most recent call last)
Cell In [5], line 4
      1 nwbfile_path = "/home/alessio/Documents/data/debug/ecephys_632269_2022-10-13_15-41-42_zarr.nwb"
      3 io = NWBZarrIO(nwbfile_path, "r")
----> 4 nwbfile = io.read()

File ~/anaconda3/envs/nwb/lib/python3.9/site-packages/hdmf/utils.py:645, in docval.<locals>.dec.<locals>.func_call(*args, **kwargs)
    643 def func_call(*args, **kwargs):
    644     pargs = _check_args(args, kwargs)
--> 645     return func(args[0], **pargs)

File ~/anaconda3/envs/nwb/lib/python3.9/site-packages/hdmf/backends/io.py:38, in HDMFIO.read(self, **kwargs)
     35 @docval(returns='the Container object that was read in', rtype=Container)
     36 def read(self, **kwargs):
     37     """Read a container from the IO source."""
---> 38     f_builder = self.read_builder()
     39     if all(len(v) == 0 for v in f_builder.values()):
     40         # TODO also check that the keys are appropriate. print a better error message
     41         raise UnsupportedOperation('Cannot build data. There are no values.')

File ~/anaconda3/envs/nwb/lib/python3.9/site-packages/hdmf/utils.py:645, in docval.<locals>.dec.<locals>.func_call(*args, **kwargs)
    643 def func_call(*args, **kwargs):
    644     pargs = _check_args(args, kwargs)
--> 645     return func(args[0], **pargs)

File ~/anaconda3/envs/nwb/lib/python3.9/site-packages/hdmf_zarr/backend.py:937, in ZarrIO.read_builder(self)
    935 @docval(returns='a GroupBuilder representing the NWB Dataset', rtype='GroupBuilder')
    936 def read_builder(self):
--> 937     f_builder = self.__read_group(self.__file, ROOT_NAME)
    938     return f_builder

File ~/anaconda3/envs/nwb/lib/python3.9/site-packages/hdmf_zarr/backend.py:973, in ZarrIO.__read_group(self, zarr_obj, name)
    971 # read sub groups
    972 for sub_name, sub_group in zarr_obj.groups():
--> 973     sub_builder = self.__read_group(sub_group, sub_name)
    974     ret.set_group(sub_builder)
    976 # read sub datasets

File ~/anaconda3/envs/nwb/lib/python3.9/site-packages/hdmf_zarr/backend.py:973, in ZarrIO.__read_group(self, zarr_obj, name)
    971 # read sub groups
    972 for sub_name, sub_group in zarr_obj.groups():
--> 973     sub_builder = self.__read_group(sub_group, sub_name)
    974     ret.set_group(sub_builder)
    976 # read sub datasets

File ~/anaconda3/envs/nwb/lib/python3.9/site-packages/hdmf_zarr/backend.py:973, in ZarrIO.__read_group(self, zarr_obj, name)
    971 # read sub groups
    972 for sub_name, sub_group in zarr_obj.groups():
--> 973     sub_builder = self.__read_group(sub_group, sub_name)
    974     ret.set_group(sub_builder)
    976 # read sub datasets

File ~/anaconda3/envs/nwb/lib/python3.9/site-packages/hdmf_zarr/backend.py:982, in ZarrIO.__read_group(self, zarr_obj, name)
    979     ret.set_dataset(sub_builder)
    981 # read the links
--> 982 self.__read_links(zarr_obj=zarr_obj, parent=ret)
    984 self._written_builders.set_written(ret)  # record that the builder has been written
    985 self.__set_built(zarr_obj, ret)

File ~/anaconda3/envs/nwb/lib/python3.9/site-packages/hdmf_zarr/backend.py:1008, in ZarrIO.__read_links(self, zarr_obj, parent)
   1006     l_path = os.path.join(link['source'], link['path'].lstrip("/"))
   1007 if not os.path.exists(l_path):
-> 1008     raise ValueError("Found bad link %s in %s to %s" % (link_name, self.__path, l_path))
   1010 target_name = str(os.path.basename(l_path))
   1011 target_zarr_obj = zarr.open(l_path, mode='r')

ValueError: Found bad link device in /home/alessio/Documents/data/debug/ecephys_632269_2022-10-13_15-41-42_zarr.nwb to results/ecephys_632269_2022-10-13_15-41-42_zarr.nwb/general/devices/Device
```

After debugging, the `l_path` is indeed the path on my remote machine. I think saving links relative to the zarr root should fix it.

### PR DESCRIPTION
**Pull request by oruebel**
Fix #44 
 

- [X]  Add tutorial to show how to create and NWB file using Zarr (the file includes links so we can use it for debugging the issue with links)
- [X] Add use of extlinks in Sphinx  
- [X] Fix bug in requirements defined in setup.py
- [ ] Add tests to check reading of links where we change the current directory (using relative path to create the file and then reading from a different current directory)

### CODE REVIEW

**Comment by oruebel** [comment]
Currently, references/links use the path provided by the user to ZarrIO as the source path for the current file. Because of this, links can break even without moving the data to another system. If we create the file with a relative path  (e.g., just the filename ``"ecephys_tutorial.nwb.zarr"`` in the tutorial), then the filepath (and hence all links) are in effect relative to the current working directory.  To break links, we then only need to change the current working directory with ``os.chdir``. Here an example of how a link currently looks in the Zarr file create by the new tutorial:

  
Screen Shot 2022-12-14 at 2 45 30 AM

Instead of listing ``source: ecephys_tutorial.nwb.zarr`` the ``source`` should be relative to the Zarr file itself, i.e., if the link is to an object within the same file the ``source`` should be either empty string or ``"."``.

**Comment by oruebel** [comment]
@mavaylon1 can you check on the failing test pipelines. There was an error in ``setup.py`` that I fixed, but there are still several errors in the pipelines that seem to be unrelated to this PR, but seem to be due to the setup of the pipelines. 

```
ERROR: Cannot install hdmf-zarr 0.post0.dev1 (from /home/runner/work/hdmf-zarr/hdmf-zarr) and hdmf-zarr 0.post0.dev1 (from /home/runner/work/hdmf-zarr/hdmf-zarr/.tox/.tmp/package/1/hdmf_zarr-0.post0.dev1-0.editable-py3-none-any.whl) because these package versions have conflicting dependencies.
```  

I think this may be same error with tox4 that @rly fixed for PyNWB in this PR https://github.com/NeurodataWithoutBorders/pynwb/pull/1608 

For (at least some of) the failing 3.7 tests it looks like the gallery tests are failing because the gallery files are not found. Maybe there is an issue with setting the working directory in the pipeline?

**Comment by mavaylon1** [comment]
@oruebel I merged the pipeline updates but for some reason the paths are throwing errors still with the windows path using "\\" instead of "/". I'll continue to dig around and hopefully can get this resolved by the end of tomorrow for a release this week.

**Comment by oruebel** [comment]
@mavaylon1 thanks for taking a look at this and for keeping me posted

**Comment by mavaylon1** [comment]
@oruebel @rly so looking at the traceback for why the gallery tests are failing I see that it is because of the new tutorials added.
The issue with the plot_nwbzarrio.py is the same issue that comes up in #45. The issue with plot_convert_nwb.py is a user warning about ZarrIO being experimental.

Either way these are both user warnings that should be ignored due to lines 59-62 of test_gallery.py
```
with warnings.catch_warnings(record=True):
                warnings.filterwarnings(
                    "ignore", message=_experimental_warning_re, category=UserWarning
                )
```

**Comment by mavaylon1** [comment]
@rly I've fixed the user warnings issue in the gallery tests and updated to use test_gallery.py. However, now I am faced with the original issue again of certain docs not being able to be found.

Screen Shot 2022-12-21 at 11 01 36 AM

I've printed out the files in the list test_gallery.py iterates over and the files are there. What is weird is that the two files consist of one old doc and one new doc.

**Comment by mavaylon1** [comment]
What is weird is that it is the addition of plot_nwb_zarrio.py that throws the path issues. When you remove it, plot_zarr_datasetio.py can be found and plot_convert_nwb.py can also be found and returns an error regarding hdmf build (tbd later)

**Comment by mavaylon1** [comment]
If we use test.py --example in tox.ini instead of test_gallery.py then the gallery-3.10 tests pass which are required but not the 3.7. We could merge using the test.py --example and create another PR to update and figure out the issue of the gallery tests that are not required. That way the fix isn't held up.

I'll also note running python test.py --example passes in my python 3.7 environment but not here.

@oruebel @rly what are your thoughts?

**Comment by oruebel** [comment]
Since we know this is only an issue of the test pipeline. I think we could merge this PR and do the release and fix the pipeline in a separate PR.

**Comment by mavaylon1** [comment]
> 

I'll review the PR today and we can merge before the day is over. I'll set up the separate PR for the gallery.

**Review by mavaylon1 — APPROVED** [review]
Removed test_gallery,py to keep it reserved for the upcoming PR.

**Comment by alejoe91** [comment]
Thanks guys! It works perfectly on our side!

**Comment by oruebel** [comment]
> Thanks guys! It works perfectly on our side!

That is great to hear!

**Pull request merged**
