### PR TITLE
Update for zarr 2.18.0 and zarr 2.18.1

### PR DESCRIPTION
**Pull request by mavaylon1**
## Motivation

What was the reasoning behind this change? Please explain the changes briefly.
This PR is to update hdmf-zarr for changes that came n 2.18.0 and new changes in 2.18.0

2.18.0
This is in response to the failing workflows using the latest version of zarr, specifically the failing test test_fsspec_streaming.

The issue is how we are reading zarr scalar arrays. We are currently trying to directly index and access the scalar. From looking at the documentation, zarr accessed a scalar array as `z[:]`, which seems to solve the problem. I also saw that `z[()]` was another syntax that works. 

Why?
Not completely clear.
When we access a scalar array in numpy we do so with notation `[()]`. Supposedly, Zarr used to support indexing scalar arrays as `z[0]`, but that was updated to numpy standard earlier in one of the zarr version 2.#. Maybe this was a functionality that finally got flushed out fully. 

**2.18.1**
To ensure that the data being assigned is in a format that the Zarr array can handle efficiently, Zarr arrays seem to require that we set with numpy arrays, i.e., `dset[:] = np.array(data)`.

Another weird behavior is when setting a dataset of references, the current method puts the entire dataset in each index vs matching the individual reference dictionary to the index (which is what we expect). 

The solution to both is make sure the data is in an array first. 

## How to test the behavior?
```
Show how to reproduce the new behavior (can be a bug fix or a new feature)
```

## Checklist

- [x] Did you update CHANGELOG.md with your changes?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf-zarr/blob/dev/docs/CONTRIBUTING.rst) document?
- [x] Have you ensured the PR clearly describes the problem and the solution?
- [x] Is your contribution compliant with our coding style? This can be checked running `ruff` from the source directory.
- [x] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/hdmf-dev/hdmf-zarr/pulls) for the same change?
- [x] Have you included the relevant issue number using "Fix #XXX" notation where XXX is the issue number? By including "Fix #XXX" you allow GitHub to close issue #XXX when the PR is merged.

### CODE REVIEW

**Comment by mavaylon1** [comment]
Hey @oruebel can you give me your thoughts. I believe this is related to #192

**Comment by oruebel** [comment]
Using the `[()]` syntax to access scalars makes sense to me

**Comment by mavaylon1** [comment]
@oruebel There are also some deprecation warnings for zarr 3.0. I will add filters in this PR, but I'll also make a ticket for those deprecations to be resolved to whatever zarr will be pivoting to.

**Comment by mavaylon1** [comment]
Review Notes:
I need to ping to see if this now resolved with this update or to see what changes:
https://github.com/hdmf-dev/hdmf-zarr/issues/192

**Review by rly — APPROVED** [review]
LGTM. Thanks for taking care of this.

**Pull request merged**
