### PR TITLE
Update to support python 3.12

### PR DESCRIPTION
**Pull request by mavaylon1**
## Motivation

What was the reasoning behind this change? Please explain the changes briefly.
Support python 3.12

## How to test the behavior?
```
Show how to reproduce the new behavior (can be a bug fix or a new feature)
```

## Checklist

- [x] Did you update CHANGELOG.md with your changes?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf-zarr/blob/dev/docs/CONTRIBUTING.rst) document?
- [x] Have you ensured the PR clearly describes the problem and the solution?
- [x] Is your contribution compliant with our coding style? This can be checked running `ruff` from the source directory.
- [x] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/hdmf-dev/hdmf-zarr/pulls) for the same change?
- [x] Have you included the relevant issue number using "Fix #XXX" notation where XXX is the issue number? By including "Fix #XXX" you allow GitHub to close issue #XXX when the PR is merged.

### CODE REVIEW

**Comment by mavaylon1** [comment]
Note: After updating the .toml, tox, and workflows, I did a search for "3.11". I'll do another look to see what else needs to be bumped to 3.12

**Comment by mavaylon1** [comment]
@oruebel The bump to 3.12 seems to have bequeathed some gallery errors that need to be resolved. I'd like to make it a separate ticket/PR to not hold this up. Thoughts? I need to do another pass through before requesting a review.

Update: I just ended up fixing it here. A new warning filter for test_gallery.py

**Comment by mavaylon1** [comment]
Review Note: I did not update the changelog since this is not a user facing update.

**Comment by rly** [comment]
> Review Note: I did not update the changelog since this is not a user facing update.

Please add a changelog -- The changelog is for any change to the software, and is for both users and developers, especially to check for changes that affect compatibility (here, for example, we announce that PyNWB is officially compatible with Python 3.12 - some downstream packages do not support Python 3.12 because pynwb does not so it's important for us to announce this). 

In contrast, when making changes to the schema repo, the schema release notes should not be updated when there are no changes to the schema files. We could add a changelog there for all changes to the repo, but its not really necessary because the main purpose of the schema repo is to hold the schema files. The surrounding code is for internal use.

**Comment by rly** [comment]
I mean HDMF-Zarr, not PyNWB, though my example about downstream packages not supporting a version of Python because PyNWB does not officially support is is true for PyNWB, not HDMF-Zarr (AFAIK)

**Comment by mavaylon1** [comment]
> I mean HDMF-Zarr, not PyNWB, though my example about downstream packages not supporting a version of Python because PyNWB does not officially support is is true for PyNWB, not HDMF-Zarr (AFAIK)

Got it. Done.

**Review by rly — APPROVED** [review]

**Pull request merged**
