### PR TITLE
Xarray Support

### LINKED ISSUE #176: [Feature]: write `xarray`-compatible Zarr files
### What would you like to see added to HDMF-ZARR?

Xarray supports the Zarr backend, but requires the `_ARRAY_DIMENSIONS` attribute to be set with a list of names for the array dimensions (e.g. `[samples, channels]`) - see https://docs.xarray.dev/en/stable/internals/zarr-encoding-spec.html#zarr-encoding

It would be great to add these attributes as default for known data types (e.g. `ElectricalSeries`)

@jsiegle

### Is your feature request related to a problem?

NWB-Zarr files cannot be opened by `xarray.open_zarr`

### What solution would you like?

Adding the `_ARRAY_DIMENSIONS` attributes to all "known" neurodata_types

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf-zarr/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf-zarr/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/hdmf-dev/hdmf-zarr/issues)?

### PR DESCRIPTION
**Pull request by mavaylon1**
## Motivation
Fix #176 

What was the reasoning behind this change? Please explain the changes briefly.

## How to test the behavior?
```
Show how to reproduce the new behavior (can be a bug fix or a new feature)
```

## Checklist

- [x] Did you update CHANGELOG.md with your changes?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf-zarr/blob/dev/docs/CONTRIBUTING.rst) document?
- [x] Have you ensured the PR clearly describes the problem and the solution?
- [x] Is your contribution compliant with our coding style? This can be checked running `ruff` from the source directory.
- [x] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/hdmf-dev/hdmf-zarr/pulls) for the same change?
- [x] Have you included the relevant issue number using "Fix #XXX" notation where XXX is the issue number? By including "Fix #XXX" you allow GitHub to close issue #XXX when the PR is merged.

### CODE REVIEW

**Comment by alejoe91** [comment]
@mavaylon1 thanks for moving on with this request. One question: will electrical series (for example) automatically set their own dimension labels automatically? Or is there any action to be taken by the user to enable this Xarray support?

**Comment by mavaylon1** [comment]
@alejoe91 The labels just need to be in the schema. If it is there, then it will be handled automatically. Since ElectricalSeries has labels as dims, it will be there without user input.

**Comment by stephprince** [comment]
This looks good on the hdmf-zarr side, but I tried testing out opening an `ElectricalSeries` Zarr dataset with xarray and I think `_ARRAY_DIMENSIONS` is not getting added to all datasets.

I've also not worked much with Zarr/xarray so I might be just setting this up incorrectly. From looking into it briefly, I think  [this call to DatasetBuilder](https://github.com/hdmf-dev/hdmf/blob/a98e5e98cbfb6e824fb57eb5e7eac1dc6cd4532b/src/hdmf/build/objectmapper.py#L1099) does not have the `dimension_labels` argument added. 

```python
import os
import numpy as np
import xarray

from numcodecs import Blosc
from pynwb.testing.mock.ecephys import mock_Device, mock_ElectrodeGroup, mock_ElectrodeTable
from pynwb.testing.mock.file import mock_NWBFile
from pynwb.ecephys import ElectricalSeries
from hdmf.common import DynamicTableRegion
from hdmf_zarr.nwb import NWBZarrIO
from hdmf_zarr import ZarrDataIO

# create nwb file
device = mock_Device()
group = mock_ElectrodeGroup(device=device)
electrodes_table = mock_ElectrodeTable(group=group)
electrodes = DynamicTableRegion(name="electrodes", data=list(range(5)), table=electrodes_table, description="electrodes")
nwbfile = mock_NWBFile(electrode_groups=[group], 
                       electrodes=electrodes_table, 
                       devices=[device])

data_with_zarr_data_io = ZarrDataIO(
    data=np.random.randn(100, 5),
    chunks=(10, 10),
    fillvalue=0,
    compressor=Blosc(cname='zstd', clevel=3, shuffle=Blosc.SHUFFLE)
)

nwbfile.add_acquisition(
    ElectricalSeries(
        name="ElectricalSeries",
        data=data_with_zarr_data_io,
        electrodes=electrodes,
        rate=30.0
    )
)

# write file
path = "zarr_testing.nwb.zarr"
absolute_path = os.path.abspath(path)
with NWBZarrIO(path=path, mode="w") as io:
    io.write(nwbfile)

# open with xarray
xarray.open_zarr(path)  # fails
xarray.open_zarr("zarr_testing.nwb.zarr/general/extracellular_ephys/electrodes/")  # works
xarray.open_zarr("zarr_testing.nwb.zarr/acquisition/ElectricalSeries")  # fails
```

**Review by stephprince — APPROVED** [review]
Approving this PR since this is working on the hdmf-zarr side if dimension_labels are stored in the builder.

A related issue to add dimension_labels support to the section of the ObjectMapper used when adding ElectricalSeries datasets is already open here: https://github.com/hdmf-dev/hdmf/issues/1163

**Pull request merged**
