### PR TITLE
Fix nwb tutorial bug

### LINKED ISSUE #55: Dimension warning for ElectricalSeries in NWBZarrIO Tutorial
The tutorial for [Creating NWB files using NWBZarrIO](https://hdmf-zarr.readthedocs.io/en/dev/tutorials/plot_nwb_zarrio.html#sphx-glr-tutorials-plot-nwb-zarrio-py) currently raises the following warnings:

```
/home/docs/checkouts/readthedocs.org/user_builds/hdmf-zarr/envs/dev/lib/python3.7/site-packages/pynwb/ecephys.py:93: UserWarning: The second dimension of data does not match the length of electrodes. Your data may be transposed.
  warnings.warn("The second dimension of data does not match the length of electrodes. Your data may be "
/home/docs/checkouts/readthedocs.org/user_builds/hdmf-zarr/envs/dev/lib/python3.7/site-packages/pynwb/ecephys.py:93: UserWarning: The second dimension of data does not match the length of electrodes. Your data may be transposed.
  warnings.warn("The second dimension of data does not match the length of electrodes. Your data may be "
```

It appears that those warnings are due to errors in the tutorial itself regarding the initialization of the test data, rather than being a bug in the library itself.

### LINKED ISSUE #59: PyNWB warnings in plot_convert_nwb_hdf5.py
The tutorial ``plot_convert_nwb_hdf5.py`` currently raises the following warnings.

```
/Users/oruebel/Devel/nwb/pynwb/src/pynwb/core.py:47: UserWarning: OpticalSeries 'StimulusPresentation_encoding': The number of frame indices in 'starting_frame' should have the same length as 'external_file'.
  warn(error_msg)
/Users/oruebel/Devel/nwb/pynwb/src/pynwb/core.py:47: UserWarning: OpticalSeries 'StimulusPresentation_encoding': Either external_file or data must be specified (not None), but not both.
  warn(error_msg)
```

 These warnings were added in the latest version of PyNWB and it appears to be an issue with the data on DANDI itself rather than being an issue in the tutorial or HDMF-Zarr. Changing the dataset that is being used should address this issue.

### PR DESCRIPTION
**Pull request by oruebel**
Fix #55
Fix #59

### CODE REVIEW

**Comment by bendichter** [comment]
@oruebel any idea what is causing problems with py3.7?

**Comment by oruebel** [comment]
> @oruebel any idea what is causing problems with py3.7?

@mavaylon1  and @rly are working on the Python 3.7 pipelines in https://github.com/hdmf-dev/hdmf-zarr/pull/53

**Comment by mavaylon1** [comment]
Is this still ready for a review? @oruebel

**Comment by oruebel** [comment]
@mavaylon1 this PR is ready for review

**Comment by mavaylon1** [comment]
@oruebel I'll look now and we can merge this right away. That way I can pull it into #53 and revert some of my changes to version reqs.

**Review by mavaylon1 — APPROVED** [review]

**Comment by oruebel** [comment]
I can't tell whether the failing runs are due to problems here or because of changes pending in #53 I'll merge these changes and then we can debug in #53

**Comment by mavaylon1** [comment]
@oruebel are you able to merge without passing the required tests?

**Comment by oruebel** [comment]
I temporarily changed the settings to allow bypassing of checks for admins

**Pull request merged**
