### PR TITLE
[CI]: Compare vs. last commit in black CI action

### PR DESCRIPTION
**Pull request by sneakers-the-rat**
## Motivation

Noticed that black wasn't being run in https://github.com/hdmf-dev/hdmf-zarr/actions/runs/7335433157/job/19973345812#step:4:66 , presumably because at the time of a PR the changes have already been committed, see https://pre-commit.com/#usage-in-continuous-integration

I assume it's intended to check if PRs are black-compliant? but isn't currently doing that. I ran a manual check of black and it looks like most of the package isn't either, so this will cause all other PRs to fail until upstream has been black reformatted. 

## How to test the behavior?

make new PR, make black-noncompliant changes, tests should fail.

## Checklist

- [ ] Did you update CHANGELOG.md with your changes?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf-zarr/blob/dev/docs/CONTRIBUTING.rst) document?
- [x] Have you ensured the PR clearly describes the problem and the solution?
- [x] Is your contribution compliant with our coding style? This can be checked running `ruff` from the source directory.
- [x] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/hdmf-dev/hdmf-zarr/pulls) for the same change?
- [x] Have you included the relevant issue number using "Fix #XXX" notation where XXX is the issue number? By including "Fix #XXX" you allow GitHub to close issue #XXX when the PR is merged.

### CODE REVIEW

**Comment by rly** [comment]
After #153 and #146 have been merged, @mavaylon1 can you reformat the repo using `black` and push those changes in a separate PR?

**Comment by mavaylon1** [comment]
> After #153 and #146 have been merged, @mavaylon1 can you reformat the repo using `black` and push those changes in a separate PR? 

Sure thing

**Comment by mavaylon1** [comment]
For now we decided to not support black and will remove the workflow.

**Comment by sneakers-the-rat** [comment]
Ha ok yes fair enough, that is one way of handling it without needing to do a bazillion line reformatting PR :)

**Pull request closed without merging**
