### PR TITLE
default load_namespace 

### LINKED ISSUE #198: [Feature]: NWBZarrIO should have load_namespaces=True by default
### What would you like to see added to HDMF-ZARR?

Following this change in PyNWB https://github.com/NeurodataWithoutBorders/pynwb/pull/1748

### Is your feature request related to a problem?

_No response_

### What solution would you like?

Consistency between NWBHDF5IO and NWBZarrIO

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf-zarr/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf-zarr/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/hdmf-dev/hdmf-zarr/issues)?

### PR DESCRIPTION
**Pull request by mavaylon1**
## Motivation

What was the reasoning behind this change? Please explain the changes briefly.
Fix #198 

## How to test the behavior?
```
Show how to reproduce the new behavior (can be a bug fix or a new feature)
```

## Checklist

- [x] Did you update CHANGELOG.md with your changes?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf-zarr/blob/dev/docs/CONTRIBUTING.rst) document?
- [x] Have you ensured the PR clearly describes the problem and the solution?
- [x] Is your contribution compliant with our coding style? This can be checked running `ruff` from the source directory.
- [x] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/hdmf-dev/hdmf-zarr/pulls) for the same change?
- [x] Have you included the relevant issue number using "Fix #XXX" notation where XXX is the issue number? By including "Fix #XXX" you allow GitHub to close issue #XXX when the PR is merged.

### CODE REVIEW

**Comment by mavaylon1** [comment]
@rly Looking at the pynwb version of this (https://github.com/NeurodataWithoutBorders/pynwb/pull/1748/files#) I don't see any tests that tries to read a file with extensions. As a result, there isn't any tests I see that need to be updated. Maybe added, but I'm fine with that being a coverage PR.

**Comment by mavaylon1** [comment]
the ruff error is fixed in a different PR (the zarr append PR)

**Comment by rly** [comment]
This looks good to me. Please add a changelog

**Comment by mavaylon1** [comment]
@stephprince already approved by ryan. Just needed a changelog

**Review by stephprince — APPROVED** [review]

**Pull request merged**
